name: Monitor Aria2 Releases

on:
  workflow_dispatch:

jobs:
  prepare_assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Release Info
        run: |
          REPO="aria2/aria2"
          API_URL="https://api.github.com/repos/$REPO/releases/latest"
          RELEASE_DATA=$(curl -s $API_URL)
          echo "$RELEASE_DATA" > release_data.json

      - name: Parse Assets
        run: |
          python3 assets/parse_assets.py release_data.json
          
      - name: Debug File Paths
        run: |
          echo "Current working directory: $PWD"
          ls -l
          echo "Contents of GITHUB_WORKSPACE:"
          ls -l "$GITHUB_WORKSPACE"

      - name: Download and Package Assets
        run: |
          chmod +x ./assets/download_assets.sh
          ./assets/download_assets.sh
          
      - name: Debug File Paths
        run: |
          echo "Current working directory: $PWD"
          ls -l
          echo "Contents of GITHUB_WORKSPACE:"
          ls -l "$GITHUB_WORKSPACE"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
