name: Monitor Aria2 Releases

on:
  schedule:
    - cron: '0 * * * *' # 每小时检查一次
  workflow_dispatch: # 允许手动触发

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          sudo apt-get update && sudo apt-get install -y jq  # Ensure jq is installed

      - name: Check for new release and get download URLs
        id: check_release
        run: |
          python .github/scripts/check_release.py
        shell: bash

      - name: Debug Print DOWNLOAD_URLS
        if: steps.check_release.outputs.new_version != ''
        run: |
          echo "DEBUG: DOWNLOAD_URLS=${{ steps.check_release.outputs.download_urls }}"
          echo "DEBUG: New Version=${{ steps.check_release.outputs.new_version }}"

      - name: Download and process new release
        if: steps.check_release.outputs.new_version != ''
        id: download_process
        run: |
          NEW_VERSION=${{ steps.check_release.outputs.new_version }}
          DOWNLOAD_URLS=${{ steps.check_release.outputs.download_urls }}

          # Ensure DOWNLOAD_URLS is a valid JSON array and not empty
          if [[ -z "$DOWNLOAD_URLS" ]]; then
            echo "No download URLs found."
            exit 1
          fi

          mkdir -p downloads
          cd downloads

          # Use a temporary file to store the JSON string, ensuring proper handling
          echo "$DOWNLOAD_URLS" > urls.json

          # Parse the JSON array of URLs using jq and iterate over them
          while IFS= read -r url; do
            filename=$(basename "$url")
            echo "Attempting to download from: $url"
            curl -L -o "$filename" "$url"
            if [[ $filename == *"64bit"* ]]; then
              unzip "$filename" -d "aria2-${NEW_VERSION}-win-64bit-build1"
              cp ../dl.bat "aria2-${NEW_VERSION}-win-64bit-build1/"
              zip -r "aria2-${NEW_VERSION}-win-64bit-build1-with-dl-bat.zip" "aria2-${NEW_VERSION}-win-64bit-build1"
            elif [[ $filename == *"32bit"* ]]; then
              unzip "$filename" -d "aria2-${NEW_VERSION}-win-32bit-build1"
              cp ../dl.bat "aria2-${NEW_VERSION}-win-32bit-build1/"
              zip -r "aria2-${NEW_VERSION}-win-32bit-build1-with-dl-bat.zip" "aria2-${NEW_VERSION}-win-32bit-build1"
            fi
          done < <(jq -r '.[]' urls.json)

          # Clean up temporary file
          rm urls.json
        shell: bash

      - name: Create Release
        if: steps.download_process.outcome == 'success'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.check_release.outputs.new_version }}
          name: "Aria2 with dl.bat included"
          body: "This release includes the original Aria2 binaries along with a custom dl.bat script."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        if: steps.create_release.outcome == 'success'
        run: |
          NEW_VERSION=${{ steps.check_release.outputs.new_version }}
          gh release upload "v${NEW_VERSION}" \
            "downloads/aria2-${NEW_VERSION}-win-64bit-build1-with-dl-bat.zip" \
            "downloads/aria2-${NEW_VERSION}-win-32bit-build1-with-dl-bat.zip" \
            --clobber
        shell: bash
